// Generated by gencpp from file base_node/MVServ.msg
// DO NOT EDIT!


#ifndef BASE_NODE_MESSAGE_MVSERV_H
#define BASE_NODE_MESSAGE_MVSERV_H

#include <ros/service_traits.h>


#include <base_node/MVServRequest.h>
#include <base_node/MVServResponse.h>


namespace base_node
{

struct MVServ
{

typedef MVServRequest Request;
typedef MVServResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MVServ
} // namespace base_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::base_node::MVServ > {
  static const char* value()
  {
    return "a5027d7394e6db0c454d58003c11ba06";
  }

  static const char* value(const ::base_node::MVServ&) { return value(); }
};

template<>
struct DataType< ::base_node::MVServ > {
  static const char* value()
  {
    return "base_node/MVServ";
  }

  static const char* value(const ::base_node::MVServ&) { return value(); }
};


// service_traits::MD5Sum< ::base_node::MVServRequest> should match 
// service_traits::MD5Sum< ::base_node::MVServ > 
template<>
struct MD5Sum< ::base_node::MVServRequest>
{
  static const char* value()
  {
    return MD5Sum< ::base_node::MVServ >::value();
  }
  static const char* value(const ::base_node::MVServRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_node::MVServRequest> should match 
// service_traits::DataType< ::base_node::MVServ > 
template<>
struct DataType< ::base_node::MVServRequest>
{
  static const char* value()
  {
    return DataType< ::base_node::MVServ >::value();
  }
  static const char* value(const ::base_node::MVServRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::base_node::MVServResponse> should match 
// service_traits::MD5Sum< ::base_node::MVServ > 
template<>
struct MD5Sum< ::base_node::MVServResponse>
{
  static const char* value()
  {
    return MD5Sum< ::base_node::MVServ >::value();
  }
  static const char* value(const ::base_node::MVServResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_node::MVServResponse> should match 
// service_traits::DataType< ::base_node::MVServ > 
template<>
struct DataType< ::base_node::MVServResponse>
{
  static const char* value()
  {
    return DataType< ::base_node::MVServ >::value();
  }
  static const char* value(const ::base_node::MVServResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASE_NODE_MESSAGE_MVSERV_H
