// Generated by gencpp from file base_node/OverSrv.msg
// DO NOT EDIT!


#ifndef BASE_NODE_MESSAGE_OVERSRV_H
#define BASE_NODE_MESSAGE_OVERSRV_H

#include <ros/service_traits.h>


#include <base_node/OverSrvRequest.h>
#include <base_node/OverSrvResponse.h>


namespace base_node
{

struct OverSrv
{

typedef OverSrvRequest Request;
typedef OverSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OverSrv
} // namespace base_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::base_node::OverSrv > {
  static const char* value()
  {
    return "ed5c22717a93863499734f374ca8e9a3";
  }

  static const char* value(const ::base_node::OverSrv&) { return value(); }
};

template<>
struct DataType< ::base_node::OverSrv > {
  static const char* value()
  {
    return "base_node/OverSrv";
  }

  static const char* value(const ::base_node::OverSrv&) { return value(); }
};


// service_traits::MD5Sum< ::base_node::OverSrvRequest> should match 
// service_traits::MD5Sum< ::base_node::OverSrv > 
template<>
struct MD5Sum< ::base_node::OverSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::base_node::OverSrv >::value();
  }
  static const char* value(const ::base_node::OverSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_node::OverSrvRequest> should match 
// service_traits::DataType< ::base_node::OverSrv > 
template<>
struct DataType< ::base_node::OverSrvRequest>
{
  static const char* value()
  {
    return DataType< ::base_node::OverSrv >::value();
  }
  static const char* value(const ::base_node::OverSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::base_node::OverSrvResponse> should match 
// service_traits::MD5Sum< ::base_node::OverSrv > 
template<>
struct MD5Sum< ::base_node::OverSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::base_node::OverSrv >::value();
  }
  static const char* value(const ::base_node::OverSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_node::OverSrvResponse> should match 
// service_traits::DataType< ::base_node::OverSrv > 
template<>
struct DataType< ::base_node::OverSrvResponse>
{
  static const char* value()
  {
    return DataType< ::base_node::OverSrv >::value();
  }
  static const char* value(const ::base_node::OverSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASE_NODE_MESSAGE_OVERSRV_H
