// Generated by gencpp from file base_node/OverSrvRequest.msg
// DO NOT EDIT!


#ifndef BASE_NODE_MESSAGE_OVERSRVREQUEST_H
#define BASE_NODE_MESSAGE_OVERSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_node
{
template <class ContainerAllocator>
struct OverSrvRequest_
{
  typedef OverSrvRequest_<ContainerAllocator> Type;

  OverSrvRequest_()
    : over_flg(0)  {
    }
  OverSrvRequest_(const ContainerAllocator& _alloc)
    : over_flg(0)  {
  (void)_alloc;
    }



   typedef int32_t _over_flg_type;
  _over_flg_type over_flg;




  typedef boost::shared_ptr< ::base_node::OverSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_node::OverSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OverSrvRequest_

typedef ::base_node::OverSrvRequest_<std::allocator<void> > OverSrvRequest;

typedef boost::shared_ptr< ::base_node::OverSrvRequest > OverSrvRequestPtr;
typedef boost::shared_ptr< ::base_node::OverSrvRequest const> OverSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_node::OverSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_node::OverSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_node::OverSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_node::OverSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_node::OverSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_node::OverSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_node::OverSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_node::OverSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_node::OverSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27cbf5183d3654cc200ef0b2bc3c0ae5";
  }

  static const char* value(const ::base_node::OverSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27cbf5183d3654ccULL;
  static const uint64_t static_value2 = 0x200ef0b2bc3c0ae5ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_node::OverSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_node/OverSrvRequest";
  }

  static const char* value(const ::base_node::OverSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_node::OverSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 over_flg\n\
";
  }

  static const char* value(const ::base_node::OverSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_node::OverSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.over_flg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OverSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_node::OverSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_node::OverSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "over_flg: ";
    Printer<int32_t>::stream(s, indent + "  ", v.over_flg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_NODE_MESSAGE_OVERSRVREQUEST_H
