// Generated by gencpp from file light_node/LightSrv.msg
// DO NOT EDIT!


#ifndef LIGHT_NODE_MESSAGE_LIGHTSRV_H
#define LIGHT_NODE_MESSAGE_LIGHTSRV_H

#include <ros/service_traits.h>


#include <light_node/LightSrvRequest.h>
#include <light_node/LightSrvResponse.h>


namespace light_node
{

struct LightSrv
{

typedef LightSrvRequest Request;
typedef LightSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LightSrv
} // namespace light_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::light_node::LightSrv > {
  static const char* value()
  {
    return "880a7d45ae2b2447f4ed19a09614d287";
  }

  static const char* value(const ::light_node::LightSrv&) { return value(); }
};

template<>
struct DataType< ::light_node::LightSrv > {
  static const char* value()
  {
    return "light_node/LightSrv";
  }

  static const char* value(const ::light_node::LightSrv&) { return value(); }
};


// service_traits::MD5Sum< ::light_node::LightSrvRequest> should match 
// service_traits::MD5Sum< ::light_node::LightSrv > 
template<>
struct MD5Sum< ::light_node::LightSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::light_node::LightSrv >::value();
  }
  static const char* value(const ::light_node::LightSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::light_node::LightSrvRequest> should match 
// service_traits::DataType< ::light_node::LightSrv > 
template<>
struct DataType< ::light_node::LightSrvRequest>
{
  static const char* value()
  {
    return DataType< ::light_node::LightSrv >::value();
  }
  static const char* value(const ::light_node::LightSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::light_node::LightSrvResponse> should match 
// service_traits::MD5Sum< ::light_node::LightSrv > 
template<>
struct MD5Sum< ::light_node::LightSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::light_node::LightSrv >::value();
  }
  static const char* value(const ::light_node::LightSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::light_node::LightSrvResponse> should match 
// service_traits::DataType< ::light_node::LightSrv > 
template<>
struct DataType< ::light_node::LightSrvResponse>
{
  static const char* value()
  {
    return DataType< ::light_node::LightSrv >::value();
  }
  static const char* value(const ::light_node::LightSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LIGHT_NODE_MESSAGE_LIGHTSRV_H
