// Generated by gencpp from file light_node/LightSrvResponse.msg
// DO NOT EDIT!


#ifndef LIGHT_NODE_MESSAGE_LIGHTSRVRESPONSE_H
#define LIGHT_NODE_MESSAGE_LIGHTSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_node
{
template <class ContainerAllocator>
struct LightSrvResponse_
{
  typedef LightSrvResponse_<ContainerAllocator> Type;

  LightSrvResponse_()
    : quantized_attraction(0)
    , quantized_intensity(0)  {
    }
  LightSrvResponse_(const ContainerAllocator& _alloc)
    : quantized_attraction(0)
    , quantized_intensity(0)  {
  (void)_alloc;
    }



   typedef int32_t _quantized_attraction_type;
  _quantized_attraction_type quantized_attraction;

   typedef int32_t _quantized_intensity_type;
  _quantized_intensity_type quantized_intensity;




  typedef boost::shared_ptr< ::light_node::LightSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_node::LightSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LightSrvResponse_

typedef ::light_node::LightSrvResponse_<std::allocator<void> > LightSrvResponse;

typedef boost::shared_ptr< ::light_node::LightSrvResponse > LightSrvResponsePtr;
typedef boost::shared_ptr< ::light_node::LightSrvResponse const> LightSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_node::LightSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_node::LightSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace light_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::light_node::LightSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_node::LightSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_node::LightSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_node::LightSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_node::LightSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_node::LightSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_node::LightSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e1519ab7e1a2ef915cdb29776ebb89f";
  }

  static const char* value(const ::light_node::LightSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e1519ab7e1a2ef9ULL;
  static const uint64_t static_value2 = 0x15cdb29776ebb89fULL;
};

template<class ContainerAllocator>
struct DataType< ::light_node::LightSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_node/LightSrvResponse";
  }

  static const char* value(const ::light_node::LightSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_node::LightSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 quantized_attraction\n\
int32 quantized_intensity\n\
\n\
";
  }

  static const char* value(const ::light_node::LightSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_node::LightSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.quantized_attraction);
      stream.next(m.quantized_intensity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_node::LightSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_node::LightSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "quantized_attraction: ";
    Printer<int32_t>::stream(s, indent + "  ", v.quantized_attraction);
    s << indent << "quantized_intensity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.quantized_intensity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_NODE_MESSAGE_LIGHTSRVRESPONSE_H
