// Generated by gencpp from file light_node/LightSrvRequest.msg
// DO NOT EDIT!


#ifndef LIGHT_NODE_MESSAGE_LIGHTSRVREQUEST_H
#define LIGHT_NODE_MESSAGE_LIGHTSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace light_node
{
template <class ContainerAllocator>
struct LightSrvRequest_
{
  typedef LightSrvRequest_<ContainerAllocator> Type;

  LightSrvRequest_()
    : req(0)  {
    }
  LightSrvRequest_(const ContainerAllocator& _alloc)
    : req(0)  {
  (void)_alloc;
    }



   typedef int32_t _req_type;
  _req_type req;




  typedef boost::shared_ptr< ::light_node::LightSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::light_node::LightSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LightSrvRequest_

typedef ::light_node::LightSrvRequest_<std::allocator<void> > LightSrvRequest;

typedef boost::shared_ptr< ::light_node::LightSrvRequest > LightSrvRequestPtr;
typedef boost::shared_ptr< ::light_node::LightSrvRequest const> LightSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::light_node::LightSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::light_node::LightSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace light_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::light_node::LightSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::light_node::LightSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_node::LightSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::light_node::LightSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_node::LightSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::light_node::LightSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::light_node::LightSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "688ec893d5ff2cccc11b9bc8bc41109b";
  }

  static const char* value(const ::light_node::LightSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x688ec893d5ff2cccULL;
  static const uint64_t static_value2 = 0xc11b9bc8bc41109bULL;
};

template<class ContainerAllocator>
struct DataType< ::light_node::LightSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "light_node/LightSrvRequest";
  }

  static const char* value(const ::light_node::LightSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::light_node::LightSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 req\n\
";
  }

  static const char* value(const ::light_node::LightSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::light_node::LightSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::light_node::LightSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::light_node::LightSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "req: ";
    Printer<int32_t>::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIGHT_NODE_MESSAGE_LIGHTSRVREQUEST_H
